services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      
      # --- Neovim 設定とデータの永続化 ---
      # ホスト側の nvim_config フォルダをコンテナの設定として使う
      - ./nvim_config:/root/.config/nvim
      
      # プラグインのデータをDockerボリュームに保存（再起動しても消えないようにする）
      - nvim_data:/root/.local/share/nvim
      
      # ログや状態データを保存
      - nvim_state:/root/.local/state/nvim
      
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle install &&
      rails s -b 0.0.0.0"

volumes:
  bundle_data:
  nvim_data:  # プラグイン保存用
  nvim_state: # 状態保存用
