services:
  app:
    build: .
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - ./nvim:/root/.config/nvim
      - nvim_data:/root/.local/share/nvim
      - nvim_state:/root/.local/state/nvim
      - solargraph_cache:/root/.solargraph
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle install &&
      rails db:migrate:reset &&
      rails db:seed &&
      rails s -b 0.0.0.0"

volumes:
  bundle_data:
  nvim_data:
  nvim_state:
  solargraph_cache:
