services:
  app:
    build: .
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle

      # --- すべて名前付きボリュームに変更 ---
      - nvim_config:/root/.config/nvim
      - nvim_data:/root/.local/share/nvim
      - nvim_state:/root/.local/state/nvim

    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle install &&
      rails db:migrate:reset &&
      rails db:seed &&
      rails s -b 0.0.0.0"

volumes:
  bundle_data:
  nvim_config: # ← 追加：設定ファイル用の箱
  nvim_data:
  nvim_state:
